### ISSUE TITLE
warning_given is not initialized

### ISSUE THREAD

**Issue by nweave03** [jdelic/django-postgresql-setrole#1]
just letting you know that the global `warning_given` is not initialized after your recent update, so it raises an exception instead of being evaluated as False.

**Comment by jdelic** [comment]
@nweave03 
oops.... how embarrassing. Thank you. Will fix.

**Comment by jdelic** [comment]
fixed in 1.0.12 via f4d03db1a2cba08302bbf74c2f46f6cccc04a80e. Thanks again.
